### ISSUE TITLE
No requests after an error

### ISSUE THREAD

**Issue by soccerob** [D2klaas/Godot-4-HTTPManager#7] opened 2023-09-21 02:15 UTC
Occasionally, I get an error with one of my web requests. After that, no web requests go out. Is it possible the manager is waiting for a request to complete but it's in a stuck state? It's not necessarily an issue with the api call that I'm making, it seems random when it happens and I'm only developing locally with the api server on my local machine as well. Any ideas why no other web requests will go out after that?

**Comment by D2klaas** [comment] 2023-09-21 06:25
Hi,
is "pause_on_failure" turned on? This will stop execution of the queue after any other result except HTTP code 200 or 305. 
This shouldn't be on by default but was. I will change this to false as default.

Have a nice day!

**Comment by soccerob** [comment] 2023-09-21 20:19
Looks like "pause_on_failure" is off which must have been the default
already. I don't recall changing it. I will try to see what additional info
I can find if it happens again. I've switched to using the class as an
Autoload so that any node throughout the game can access the class and make
requests. Not sure if that's how you intended it or not, but it appears to
be working just fine that way.

**Comment by D2klaas** [comment] 2023-09-22 08:08
I was lacking behind releasing the latest version to the asset-library, maybe you had an older version where the default was different.
It was intended to use it as a node in the scene-tree, but using it as autoloaded class just inserts the node way higher up in the tree, so it shouldn't make any difference.
If you haven't any error or suspicious debug output i don't think i can help you any further from this point. Let me know if you stumble into the issue again!

**Comment by D2klaas** [comment] 2023-10-05 07:56
Since there seems no other occurrence of this problem, i will close this issue

**Closed as completed by D2klaas** 2023-10-05 07:56 UTC
